### ISSUE TITLE
Backend returning json object on rest service

### ISSUE THREAD

**Issue by kykint** [tosha-220/NgShop#15]

**Comment by Mihail-Vilms-MSU** [comment]
Добавил pojo класс , инициализировал его в контроллере, вернул его. притянул зависимость jackson.
Есть проблема: когда закинул в репозиторий эти два файла, там остался старый контроллер в папке net/ckr/shop, чё то не догоняю как его убрать с глаз долой...пока ка то так...

**Comment by Mihail-Vilms-MSU** [comment]
Всё лишнее почистил, оставшееся отформатировал, вроде всё грамотно.

**Comment by Mihail-Vilms-MSU** [comment]
Не до конца понял какой ещё code review я должен сделать, походу я что-то недопонимаю...

**Comment by kykint** [comment]
https://github.com/tosha-220/NgShop/pull/16 вот тут от тебя акцепт требуется
